### ISSUE TITLE
Failed to complete remote attestation by rats-tls with occlum mode in container

### ISSUE THREAD

**Issue by YangLiang3** [inclavare-containers/rats-tls#119]

**Comment by YangLiang3** [comment]
In container, running rats-tls with occlum mode, we have to set the PCCS's configuration option USE_SECURE_CERT=FALSE. we need to check what happened.

**Comment by YangLiang3** [comment]
By the following steps, you can run the remote attestation in rats-tls occlum mode successfully. But the step 2 and step 3 shoud not be necessary.  So please help to debug this issue.
1. It needs to preload the library: /usr/lib/x86_64-linux-gnu/libsgx_id_enclave.signed.so.* to container Env.
2. In config.json, it needs to map the host /usr/lib/x86_64-linux-gnu to container's /usr/lib/x86_64-linux-gnu
3. Modify PCCS's configuration, USE_SECURE_CERT=FALSE

**Comment by jiazhang0** [comment]
@YangLiang3 Here is the root case:

The untrusted QCNL lib provided by DCAP has different actions when parsing the so-called PCCS config file/etc/sgx_default_qcnl.conf：

```C
// Prior to SGX DCAP 1.12 / SGX SDK 2.15：parse config file when loading QCNL lib (early loading mode）
__attribute__((constructor)) void _qcnl_global_init()
{
    curl_global_init(CURL_GLOBAL_DEFAULT);

    // read configuration File
    ifstream ifs("/etc/sgx_default_qcnl.conf");
...

// After  SGX DCAP 1.13 / SGX SDK 2.16：parse config file lazily till calling QCNL Lib (lazy loading mode)
static struct init_solib {
    init_solib() {
        curl_global_init(CURL_GLOBAL_DEFAULT);
    }
} _init_solib;

bool QcnlConfigLegacy::load_config() {
    // read configuration File
    bool use_collateral_service = false;
    ifstream ifs("/etc/sgx_default_qcnl.conf");
...
```

When rune is launched, the QCNL lib from host is loaded before entering container namespace. So if the version of QNCL lib installed on host:
- <= SGX DCAP 1.12 / SGX SDK 2.15: load PCCS config file from host
- >= SGX DCAP 1.13 / SGX SDK 2.16: load PCCS config file from container rootfs

In your case, I guess you are using the QCNL lib installed on host with newer version (>= SGX DCAP 1.13 / SGX SDK 2.16), which implies the PCCS config file would be loaded from container rootfs. So please make sure the PCCS config file in container rootfs is configured correctly. Additionally, the actual certificate file used to authenticate PCCS server is loaded from the container rootfs rather than host. So maybe we need to mount the certificate files from host into container, or install the ca-certificate package in container rootfs if PCCS CA signer certificate is updated.
